### ISSUE TITLE
Inaccurate statistics

### ISSUE THREAD

**Issue by JoseDeFreitas** [jstrieb/github-stats#18] opened 2021-02-10 00:23 UTC
Hello 👋.

I followed all the steps stated in the readme file correctly. Added the correct perms, I clicked the links provided in both steps 2 and 3 and I named the secret correctly.
However, these are the generated images:

![](https://raw.githubusercontent.com/JoseDeFreitas/github-stats/3f13dc674cd8c84712b2c823f402c16fc10ff879/generated/overview.svg)
and
![](https://raw.githubusercontent.com/JoseDeFreitas/github-stats/3f13dc674cd8c84712b2c823f402c16fc10ff879/generated/languages.svg)
[My fork](https://github.com/JoseDeFreitas/github-stats)

They do not match my actual stats whatsoever.
As I wrote, I've done all the steps correctly. I tried reloading the page and re-running the workflow, but the result was the same. I don't know if it's an issue with the API or I actually did something wrong...

Thank you in advance.

**Comment by jstrieb** [comment] 2021-02-10 00:44
Hi, thanks for checking out the project and taking the time to open this issue! Which part of the statistics are looking particularly inaccurate? Despite having some popular repos, 302k+ stars does seem a bit high to me based on glancing at your profile...

In this case, the statistics include information from your forks of popular repositories. To fix this, you will want to add an environment variable to the workflow with the name `EXCLUDE_FORKED_REPOS` and a value of `true`. The place to do that is [here](https://github.com/JoseDeFreitas/github-stats/blob/fdd8f855b81314eaca42ce9b563571253c485a90/.github/workflows/main.yml#L53-L57). Adding this will remove all forked repositories from the statistics.

Alternatively, add the names of the repos whose stats you want to ignore (in owner/name format e.g., `jstrieb/github-stats` or `JoseDeFreitas/learn-python`) separated by commas to a new secret called `EXCLUDED`. I realize now that the owner/name format is not stated explicitly in the instructions, and that this may be a cause of confusion.

If things are still not working and you want to do some in-depth debugging to see which repos have which weird statistics, I recommend cloning the repo locally, and adding print statements [here](https://github.com/jstrieb/github-stats/blob/a80cdb6a8d6802acc7982e3c626ff6d2a6d8fbb0/github_stats.py#L328). Then, running `github_stats.py`. That would look like:

``` bash
git clone https://github.com/jstrieb/github-stats.git && cd github-stats
python3 -m pip install --upgrade --requirement requirements.txt
# edit in some print statements
python3 github_stats.py
```

Hopefully I've understood the stats you're concerned about and this answers your question! If not, I'm happy to work with you to drill down exactly what doesn't look right so we can fix it. Fingers crossed that this is just unexpected results from the API and not a bug in the stats code 🤞

**Comment by JoseDeFreitas** [comment] 2021-02-10 01:13
Hello @jstrieb. I didn't think of doing that. I've just added that rule to the .yml file and now it shows the stats I want it to show. Already added it to my README file on my profile (linking to this repo). So sorry for not trying that before opening the issue 🤦. Thank you for your quick response and help 👏.

**Comment by jstrieb** [comment] 2021-02-10 01:45
Hey @JoseDeFreitas! No worries, glad we were able to resolve this quickly – I would rather 100 problems like this than 1 bug in the code! Issues like these are very helpful for me anyway, so that I can improve the (unfortunately fairly difficult) setup process. Since it seems resolved I'm going to close the issue.

Thanks again for checking out the project and including the stats images in your profile README! Feel free to reach out if other weird stuff happens.

**Closed by jstrieb** 2021-02-10 01:45 UTC
