### ISSUE TITLE
Text going beyond the margin in linux

### ISSUE THREAD

**Issue by akaShivam** [jstrieb/github-stats#14] opened 2021-01-14 08:40 UTC
In the latest commit there seems to be some changes which leads to following output: 

![image](https://user-images.githubusercontent.com/41604527/104565261-08de9f00-5672-11eb-83e6-cb3929be6cbe.png)

**Comment by jstrieb** [comment] 2021-01-14 08:43
Thanks for bringing this to my attention! It's probably related to the fix I quickly pushed out for #12. I will try to take a look soon, but the key to solving it likely lies in analyzing the diff for the commit made to address that issue.

**Comment by rahul-jha98** [comment] 2021-01-24 09:32
@jstrieb Could I work on this issue??

**Comment by jstrieb** [comment] 2021-01-24 23:35
@rahul-jha98 thanks for taking an interest in this! I've been pretty busy lately and would appreciate the help getting to the bottom of this issue. I created a branch [border-fix](https://github.com/jstrieb/github-stats/tree/border-fix) that you should make a PR on if you fix it or propose a solution. I may make some edits and will then test as much as I can on different browser/OS configurations before merging. 

As I note above, this issue is probably caused by the fix for #12 ([this commit](https://github.com/jstrieb/github-stats/commit/b7e28adadeb0013669162c8a98039a06dc39e145)). 

Making everything work well in all browsers will likely be a challenge, so please note in any subsequent commits what configurations you have tested on.

**Comment by rahul-jha98** [comment] 2021-01-26 04:36
@jstrieb Thanks for guiding me to the commit as it narrowed down where I had to look to solve the issue.
After fixing the languages.svg I noticed there was a difference in alignment in generated overview.svg and languages.svg. So I have taken the liberty to modify overview.svg as well so that both are now centred wrt to their respective frames. I have created the PR for the same.

For the sake of testing from my end I have verified that the new svg works in
-  Mac OS Catalina : Safari, Chrome, Firefox
-  Manjaro 20.2.1 (for checking on Linux): Chrome, Firefox
-  Windows 10: Chrome, Firefox
 
Also, I know it isn't easy for single person to maintain the project for the rest of us and would like to thank you for creating such an awesome repo for the community. I am happy to provide the small contributions I can to help maintain the project.

**Comment by jstrieb** [comment] 2021-02-09 06:15
Sorry for the crazy delay on this! My semester just started back up, and I've been busy doing math homework.

@rahul-jha98 was kind enough to work on a fix for this issue. I verified that it works on all the devices I have access to and merged into `master`. I will leave this issue open for a couple of days just in case, but hopefully this is resolved!

**Comment by jstrieb** [comment] 2021-02-13 21:55
Since there hasn't been any more discussion on this matter, I will assume the issue is fixed.

**Closed by jstrieb** 2021-02-13 21:55 UTC
