### ISSUE TITLE
Unexpected behaviour on Safari

### ISSUE THREAD

**Issue by tavyandy97** [jstrieb/github-stats#12] opened 2020-12-27 16:31 UTC
<img width="772" alt="image" src="https://user-images.githubusercontent.com/22865691/103175311-0bc64b00-488f-11eb-90bc-0699b808db75.png">

**Comment by jstrieb** [comment] 2020-12-27 18:48
Hi, thanks for reporting this bug!

Is this Safari on mobile, or on a computer?

**Comment by tavyandy97** [comment] 2020-12-27 19:07
Hey @jstrieb !
This was on Safari on a computer

**Comment by jstrieb** [comment] 2020-12-27 19:20
Thanks for the quick response! I'm going to try and find a way to replicate this issue, despite not having a Mac. 

I suspect the issue may have something to with displaying animated SVGs. Does there seem to be any visible animation at all when the page with the GitHub stats images is reloaded (in a private/incognito window to prevent caching)? 

Do other animated SVG images work? I've attached an example below.
![Example animated SVG](https://upload.wikimedia.org/wikipedia/commons/8/87/SVG_animation_using_CSS.svg)

**Comment by tavyandy97** [comment] 2020-12-28 04:01
The issue seems to be with the SVG styling and not the animation. The animation seems to working on Safari as well (for https://github.com/jstrieb/github-stats). However, the formatting of the base SVG seems to be disturbed. I looked up other SVG's for GitHub README's and they seemed to be working fine. Hope this helps.

**Comment by jstrieb** [comment] 2021-01-13 23:30
Hi @tavyandy97! I was finally able to borrow a Mac for long enough to debug this on. As far as I can tell, the latest commit should have fixed everything without breaking anything in Chrome or Firefox.

I am closing this issue because it seems to be fixed for me, but feel free to reopen it if the problem is not totally solved. Once again, thanks for bringing this to my attention! I wouldn't have known about it otherwise.

**Closed by jstrieb** 2021-01-13 23:30 UTC
